#!/bin/sh

# Generated at Fri Nov  4 22:38:47 2016 with Daemon::Control 0.001008

### BEGIN INIT INFO
# Provides:          SMS-Messenger
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SMS Messenger
# Description:       SMS Messenger controls the SMS Messenger daemon.
### END INIT INFO`





if [ -x /usr/src/perl/sms-messenger/messenger_daemon.pl ];
then
    /usr/src/perl/sms-messenger/messenger_daemon.pl $1
else
    echo "Required program /usr/src/perl/sms-messenger/messenger_daemon.pl not found!"
    exit 1;
fi
